// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX7BXx36bEqXArgKJ2h5eSPsWYl9K4eWs',
    appId: '1:879886139612:android:d2b68672fd34e89761f419',
    messagingSenderId: '879886139612',
    projectId: 'smart-pet-feeder-d0016',
    databaseURL: 'https://smart-pet-feeder-d0016-default-rtdb.firebaseio.com',
    storageBucket: 'smart-pet-feeder-d0016.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgCfVBAeI1rQCPlAa_Y6I3Me_o-GHZAM0',
    appId: '1:879886139612:web:ba1a1ccbe83b5d9261f419',
    messagingSenderId: '879886139612',
    projectId: 'smart-pet-feeder-d0016',
    authDomain: 'smart-pet-feeder-d0016.firebaseapp.com',
    databaseURL: 'https://smart-pet-feeder-d0016-default-rtdb.firebaseio.com',
    storageBucket: 'smart-pet-feeder-d0016.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgCfVBAeI1rQCPlAa_Y6I3Me_o-GHZAM0',
    appId: '1:879886139612:web:d6682028dfe1167761f419',
    messagingSenderId: '879886139612',
    projectId: 'smart-pet-feeder-d0016',
    authDomain: 'smart-pet-feeder-d0016.firebaseapp.com',
    databaseURL: 'https://smart-pet-feeder-d0016-default-rtdb.firebaseio.com',
    storageBucket: 'smart-pet-feeder-d0016.firebasestorage.app',
  );

}