[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    bogde/HX711@^0.7.5
    madhephaestus/ESP32Servo@^0.13.0
    arduino-libraries/NTPClient@^3.2.1
    mobizt/Firebase Arduino Client Library for ESP8266 and ESP32@^4.4.14

build_flags =
    -DCORE_DEBUG_LEVEL=0

upload_speed = 921600
board_build.flash_mode = dout
